In [1]:
import pandas as pd 
import numpy as np

# 벅스, 멜론, 지니의 탑100 음원 데이터를 불러오시오 
- Bugs_Chart.csv, Genie_Chart.csv, Melon_Chart.csv

In [62]:
melon_data = pd.read_excel('./data/All_Music_chart.xlsx', sheet_name="멜론차트")
bugs_data = pd.read_excel('./data/All_Music_chart.xlsx', sheet_name="벅스차트")
genie_data = pd.read_excel('./data/All_Music_chart.xlsx', sheet_name="지니차트")


Bugs_Chart = pd.DataFrame(bugs_data)
Genie_Chart = pd.DataFrame(genie_data)
Melon_Chart = pd.DataFrame(melon_data)

bugs = Bugs_Chart.drop('Unnamed: 0', axis=1)
genie = Genie_Chart.drop('Unnamed: 0', axis=1)
melon = Melon_Chart.drop('Unnamed: 0', axis=1)

In [64]:
display(bugs)
display(genie)
display(melon)

      순위                                    곡 명                             가수
0     1위                    Upper Side Dreamin’                        ENHYPEN
1     2위                        strawberry moon                        아이유(IU)
2     3위                                   나비효과                         볼빨간사춘기
3     4위                             너는 내 세상이었어                         볼빨간사춘기
4     5위                                 Savage                          aespa
..   ...                                    ...                            ...
95   96위                                  상상더하기                     라붐(LABOUM)
96   97위  NO BREAK (Prod. GooseBumps & 사이먼 도미닉)  홀리뱅 (HolyBang)홀리뱅 (HolyBang)
97   98위                             가을 우체국 앞에서                            김대명
98   99위                                   IF I                            백지영
99  100위                 BAD GIRL (Prod. Czaer)    라치카 (LACHICA)라치카 (LACHICA)

[100 rows x 3 columns]

      순위                            곡 명                             가수
0     1위                strawberry moon                       아이유 (IU)
1     2위                           나비효과                         볼빨간사춘기
2     3위                         Savage                          aespa
3     4위                           Stay  The Kid LAROI & Justin Bieber
4     5위                            신호등                            이무진
..   ...                            ...                            ...
95   96위  비 오는 날 듣기 좋은 노래 (Feat. Colde)                             제시
96   97위                           HERO                세븐틴 (SEVENTEEN)
97   98위                   롤린 (Rollin')           브레이브걸스 (Brave girls)
98   99위                            끝사랑                            임영웅
99  100위                   매일 그대라서 행복하다                            이무진

[100 rows x 3 columns]

      순위                    곡 명                            가수
0     1위        strawberry moon                           아이유
1     2위                 Savage                         aespa
2     3위                   STAY  The Kid LAROI, Justin Bieber
3     4위                    신호등                           이무진
4     5위              사랑은 늘 도망가                           임영웅
..   ...                    ...                           ...
95   96위                     고백                      신용재 (2F)
96   97위  치맛바람 (Chi Mat Ba Ram)                        브레이브걸스
97   98위           Alcohol-Free                  TWICE (트와이스)
98   99위       사실 나는 (Feat.전건호)                          경서예지
99  100위      Love On The Floor                       NCT 127

[100 rows x 3 columns]

# 각 음원사이트에서 10위권 안의 노래들을 출력하시오

In [65]:
bugs.iloc[0:10]

    순위                    곡 명                               가수
0   1위    Upper Side Dreamin’                          ENHYPEN
1   2위        strawberry moon                          아이유(IU)
2   3위                   나비효과                           볼빨간사춘기
3   4위             너는 내 세상이었어                           볼빨간사춘기
4   5위                 Savage                            aespa
5   6위           Cold Blooded                        제시(Jessi)
6   7위                  가르치지마                       에일리(Ailee)
7   8위            My Universe  Coldplay(콜드플레이)Coldplay(콜드플레이)
8   9위  미워지지가 않아 (Unhateable)                               노을
9  10위                   STAY      The Kid LAROIThe Kid LAROI

In [66]:
genie.iloc[0:10]

    순위              곡 명                             가수
0   1위  strawberry moon                       아이유 (IU)
1   2위             나비효과                         볼빨간사춘기
2   3위           Savage                          aespa
3   4위             Stay  The Kid LAROI & Justin Bieber
4   5위              신호등                            이무진
5   6위      My Universe                       아이유 (IU)
6   7위    다정히 내 이름을 부르면                         볼빨간사춘기
7   8위   OHAYO MY NIGHT                          aespa
8   9위        사랑은 늘 도망가  The Kid LAROI & Justin Bieber
9  10위       Next Level                            이무진

In [67]:
melon.iloc[0:10]

    순위              곡 명                            가수
0   1위  strawberry moon                           아이유
1   2위           Savage                         aespa
2   3위             STAY  The Kid LAROI, Justin Bieber
3   4위              신호등                           이무진
4   5위        사랑은 늘 도망가                           임영웅
5   6위      My Universe               Coldplay, 방탄소년단
6   7위       Next Level                         aespa
7   8위    다정히 내 이름을 부르면                     경서예지, 전건호
8   9위   OHAYO MY NIGHT     디핵 (D-Hack), PATEKO (파테코)
9  10위    낙하 (with 아이유)                     AKMU (악뮤)

# 각 음원사이트에서 35위의 노래를 확인하시오

In [68]:
bugs.iloc[34]

순위          35위
곡 명    밤새 니가 내려
가수          케이시
Name: 34, dtype: object

In [69]:
genie.iloc[34]

순위                    35위
곡 명    Favorite (Vampire)
가수               아이유 (IU)
Name: 34, dtype: object

In [70]:
melon.iloc[34]

순위     35위
곡 명    끝사랑
가수     임영웅
Name: 34, dtype: object

# 각 사이트별로 탑100 순위에 있는 가수들의 이름을 구하시오

In [71]:
bugs['가수']

0                           ENHYPEN
1                           아이유(IU)
2                            볼빨간사춘기
3                            볼빨간사춘기
4                             aespa
                  ...
95                       라붐(LABOUM)
96    홀리뱅 (HolyBang)홀리뱅 (HolyBang)
97                              김대명
98                              백지영
99      라치카 (LACHICA)라치카 (LACHICA)
Name: 가수, Length: 100, dtype: object

In [72]:
genie['가수']

0                          아이유 (IU)
1                            볼빨간사춘기
2                             aespa
3     The Kid LAROI & Justin Bieber
4                               이무진
                  ...
95                               제시
96                  세븐틴 (SEVENTEEN)
97             브레이브걸스 (Brave girls)
98                              임영웅
99                              이무진
Name: 가수, Length: 100, dtype: object

In [73]:
melon['가수']

0                              아이유
1                            aespa
2     The Kid LAROI, Justin Bieber
3                              이무진
4                              임영웅
                  ...
95                        신용재 (2F)
96                          브레이브걸스
97                    TWICE (트와이스)
98                            경서예지
99                         NCT 127
Name: 가수, Length: 100, dtype: object

# 각 사이트별로 탑100 순위에 있는 가수들의 수를 구하시오

In [74]:
len(pd.unique(bugs['가수']))

70

In [75]:
len(pd.unique(genie['가수']))

31

In [76]:
len(pd.unique(melon['가수']))

56

# 각 사이트별로 각 가수들이 몇 곡씩 탑100안에 순위를 올렸는지 수를 구하시오

In [77]:
bugs['가수'].value_counts()

아이유(IU)                7
aespa                  4
세븐틴(SEVENTEEN)         3
백예린 (Yerin Baek)       3
이무진                    3
                      ..
에일리(Ailee)             1
주시크 (Joosiq)           1
Jawsh 685Jawsh 685     1
거미                     1
이해리                    1
Name: 가수, Length: 70, dtype: int64

In [78]:
genie['가수'].value_counts()

임영웅                              11
이무진                               8
아이유 (IU)                          8
세븐틴 (SEVENTEEN)                   7
볼빨간사춘기                            6
방탄소년단                             6
aespa                             6
The Kid LAROI & Justin Bieber     4
브레이브걸스 (Brave girls)              3
Justin Bieber                     2
조정석                               2
멜로망스 (MeloMance)                  2
제시                                2
NCT 127                           2
David Guetta                      2
주시크 (Joosiq)                      2
다비치                               2
헤이즈 (Heize)                       2
케이윌 (K.Will)                      2
경서예지 & 전건호                        2
MSG워너비 (M.O.M)                    2
BE'O (비오)                         2
디핵 (D-Hack) & PATEKO              2
Ed Sheeran                        2
마크툽 (Maktub)                      2
태연 (TAEYEON)                      2
AKMU (악뮤)                         2
Coldplay & 방탄소년단                  2
전소미                               1
에픽하이 (EPIK HIGH)                  1
Red Velvet (레드벨벳)                 1
Name: 가수, dtype: int64

In [79]:
melon['가수'].value_counts()

임영웅                               10
세븐틴                                9
아이유                                7
방탄소년단                              6
이무진                                3
NCT 127                            3
브레이브걸스                             3
장범준                                2
AKMU (악뮤)                          2
헤이즈 (Heize)                        2
볼빨간사춘기                             2
aespa                              2
이예준                                2
마크툽 (MAKTUB)                       2
조정석                                2
Justin Bieber                      2
STAYC(스테이씨)                        2
폴킴                                 1
Ed Sheeran                         1
송이한                                1
정동하                                1
조이 (JOY)                           1
디핵 (D-Hack), PATEKO (파테코)          1
산들                                 1
BLACKPINK                          1
TWICE (트와이스)                       1
멜로망스                               1
전소미                                1
제시 (Jessi)                         1
B.I                                1
ITZY (있지)                          1
경서예지                               1
호미들                                1
신용재 (2F)                           1
태연 (TAEYEON)                       1
김대명                                1
다비치                                1
MSG워너비(M.O.M)                      1
창모 (CHANGMO)                       1
경서예지, 전건호                          1
Red Velvet (레드벨벳)                  1
이해리 (다비치)                          1
빅마마                                1
Jawsh 685, Jason Derulo, 방탄소년단     1
Anne-Marie                         1
The Kid LAROI, Justin Bieber       1
David Guetta                       1
노을                                 1
경서                                 1
스탠딩 에그                             1
ASH ISLAND                         1
케이윌                                1
SG 워너비                             1
주시크 (Joosiq)                       1
Coldplay, 방탄소년단                    1
오마이걸 (OH MY GIRL)                  1
Name: 가수, dtype: int64

# 전체 사이트를 합산하여 가장 인기가 있는 가수 10팀을 구하시오.

In [174]:
a = bugs.가수.str.replace(r'\(.+\)', '')
a = a.str.strip()
bugs_song = b.value_counts()
df_bugs = pd.DataFrame(bugs_song)
df_bugs = df_bugs.reset_index()
display(df_bugs)

b = genie.가수.str.replace(r'\(.+\)', '')
b = b.str.strip()
genie_song = b.value_counts()
df_genie = pd.DataFrame(genie_song)
df_genie = df_genie.reset_index()
display(df_genie)

c = melon.가수.str.replace(r'\(.+\)', '')
c = c.str.strip()
melon_song = c.value_counts()
df_melon = pd.DataFrame(melon_song)
df_melon = df_melon.reset_index()
display(df_melon)

<ipython-input-174-6300b2c2e2f7>:1: FutureWarning: The default value of regex will change from True to False in a future version.
  a = bugs.가수.str.replace(r'\(.+\)', '')

                            index  가수
0                             임영웅  11
1                             아이유   8
2                             이무진   8
3                             세븐틴   7
4                           aespa   6
5                          볼빨간사춘기   6
6                           방탄소년단   6
7   The Kid LAROI & Justin Bieber   4
8                          브레이브걸스   3
9                              태연   2
10                             제시   2
11                        NCT 127   2
12                   디핵  & PATEKO   2
13                            케이윌   2
14                            조정석   2
15                  Justin Bieber   2
16                   David Guetta   2
17                           멜로망스   2
18                            헤이즈   2
19                            다비치   2
20                           BE'O   2
21                            주시크   2
22                     경서예지 & 전건호   2
23                           AKMU   2
24                            마크툽   2
25                     Ed Sheeran   2
26                         MSG워너비   2
27               Coldplay & 방탄소년단   2
28                            전소미   1
29                     Red Velvet   1
30                           에픽하이   1

<ipython-input-174-6300b2c2e2f7>:8: FutureWarning: The default value of regex will change from True to False in a future version.
  b = genie.가수.str.replace(r'\(.+\)', '')

                            index  가수
0                             임영웅  11
1                             아이유   8
2                             이무진   8
3                             세븐틴   7
4                           aespa   6
5                          볼빨간사춘기   6
6                           방탄소년단   6
7   The Kid LAROI & Justin Bieber   4
8                          브레이브걸스   3
9                              태연   2
10                             제시   2
11                        NCT 127   2
12                   디핵  & PATEKO   2
13                            케이윌   2
14                            조정석   2
15                  Justin Bieber   2
16                   David Guetta   2
17                           멜로망스   2
18                            헤이즈   2
19                            다비치   2
20                           BE'O   2
21                            주시크   2
22                     경서예지 & 전건호   2
23                           AKMU   2
24                            마크툽   2
25                     Ed Sheeran   2
26                         MSG워너비   2
27               Coldplay & 방탄소년단   2
28                            전소미   1
29                     Red Velvet   1
30                           에픽하이   1

<ipython-input-174-6300b2c2e2f7>:15: FutureWarning: The default value of regex will change from True to False in a future version.
  c = melon.가수.str.replace(r'\(.+\)', '')

                             index  가수
0                              임영웅  10
1                              세븐틴   9
2                              아이유   7
3                            방탄소년단   6
4                           브레이브걸스   3
5                              이무진   3
6                          NCT 127   3
7                              헤이즈   2
8                              이예준   2
9                            aespa   2
10                          볼빨간사춘기   2
11                   Justin Bieber   2
12                             장범준   2
13                           STAYC   2
14                            AKMU   2
15                             마크툽   2
16                             조정석   2
17                              제시   1
18                             김대명   1
19                              조이   1
20                          MSG워너비   1
21                            경서예지   1
22                            오마이걸   1
23                      Ed Sheeran   1
24                             호미들   1
25                            멜로망스   1
26                             송이한   1
27                             정동하   1
28                             B.I   1
29                              산들   1
30                       BLACKPINK   1
31                      Red Velvet   1
32                              폴킴   1
33                          SG 워너비   1
34                             전소미   1
35                             다비치   1
36                       경서예지, 전건호   1
37                             신용재   1
38                              디핵   1
39                             빅마마   1
40  Jawsh 685, Jason Derulo, 방탄소년단   1
41                             주시크   1
42                      Anne-Marie   1
43                            ITZY   1
44    The Kid LAROI, Justin Bieber   1
45                             케이윌   1
46                    David Guetta   1
47                           TWICE   1
48                              노을   1
49                              경서   1
50                          스탠딩 에그   1
51                 Coldplay, 방탄소년단   1
52                      ASH ISLAND   1
53                              태연   1
54                              창모   1
55                             이해리   1

In [187]:
from functools import reduce
songs = [df_bugs, df_genie, df_melon]
df_merge = reduce(lambda left, right: pd.merge(left, right, on='index'), songs)

df_merge['sum'] = df_merge['가수_x'] + df_merge['가수_y'] + df_merge['가수']
df_merge_sum = df_merge.sort_values(by='sum', ascending=False)

df_merge_sum.iloc[0:10]

            index  가수_x  가수_y  가수  sum
0             임영웅    11    11  10   32
3             세븐틴     7     7   9   23
1             아이유     8     8   7   23
2             이무진     8     8   3   19
6           방탄소년단     6     6   6   18
4           aespa     6     6   2   14
5          볼빨간사춘기     6     6   2   14
7          브레이브걸스     3     3   3    9
10        NCT 127     2     2   3    7
13  Justin Bieber     2     2   2    6

# 각 사이트별 차트에 아이유의 곡들을 출력하시오

In [90]:
bugs_iu = bugs[bugs.가수 == '아이유(IU)']
bugs_iu

     순위                          곡 명       가수
1    2위              strawberry moon  아이유(IU)
36  37위                          라일락  아이유(IU)
67  68위                    Celebrity  아이유(IU)
70  71위                     Blueming  아이유(IU)
73  74위  에잇(Prod.&Feat. SUGA of BTS)  아이유(IU)
74  75위                      내 손을 잡아  아이유(IU)
88  89위                  어푸 (Ah puh)  아이유(IU)

In [91]:
genie_iu = genie[genie.가수 == '아이유 (IU)']
genie_iu

     순위                                                곡 명        가수
0    1위                                    strawberry moon  아이유 (IU)
5    6위                                        My Universe  아이유 (IU)
34  35위                                 Favorite (Vampire)  아이유 (IU)
38  39위                                       별빛 같은 나의 사랑아  아이유 (IU)
55  56위                                        My Universe  아이유 (IU)
60  61위  Hey Mama (Feat. Nicki Minaj & Bebe Rexha & Afr...  아이유 (IU)
89  90위                                              비와 당신  아이유 (IU)
93  94위                                            그대라는 사치  아이유 (IU)

In [99]:
melon_iu = melon[melon.가수 == '아이유']
melon_iu

     순위                          곡 명   가수
0    1위              strawberry moon  아이유
30  31위                          라일락  아이유
32  33위                    Celebrity  아이유
48  49위                      내 손을 잡아  아이유
65  66위                     Blueming  아이유
72  73위  에잇(Prod.&Feat. SUGA of BTS)  아이유
84  85위                  어푸 (Ah puh)  아이유

# 각 사이트별로 아이유 노래들의 평균순위를 구하시오. (정수값)

In [145]:
bugs_iu_rank = bugs_iu['순위'].str.replace('위', '')
bugs_iu_df = pd.DataFrame(bugs_iu_rank)
bugs_iu_type = bugs_iu_df['순위'].astype('int')
bugs_iu_type.mean()

59.42857142857143

In [146]:
genie_iu_rank = genie_iu['순위'].str.replace('위', '')
genie_iu_df = pd.DataFrame(genie_iu_rank)
genie_iu_type = genie_iu_df['순위'].astype('int')
genie_iu_type.mean()

47.75

In [147]:
melon_iu_rank = melon_iu['순위'].str.replace('위', '')
melon_iu_df = pd.DataFrame(melon_iu_rank)
melon_iu_type = melon_iu_df['순위'].astype('int')
melon_iu_type.mean()

48.285714285714285

# 제목에  '사랑'이라는 단어가 들어가는 곡들을  출력하시오.

In [150]:
bugs[bugs['곡 명'].str.contains('사랑')]

     순위                                곡 명        가수
10  11위                         그래도 사랑이었잖아        거미
15  16위                             나의 첫사랑       다비치
26  27위                          사랑은 늘 도망가       임영웅
38  39위  사랑은 언제나 목마르다 (N번째 연애 X 이해리 (다비치))       이해리
48  49위                사랑했던 우리가 어떻게 친구가 되니       송하예
80  81위          어떻게 이별까지 사랑하겠어, 널 사랑하는 거지  AKMU(악뮤)

In [151]:
genie[genie['곡 명'].str.contains('사랑')]

     순위                 곡 명                             가수
8    9위           사랑은 늘 도망가  The Kid LAROI & Justin Bieber
13  14위              나의 첫사랑                            임영웅
31  32위  다시 사랑한다면 (김필 Ver.)                          방탄소년단
38  39위        별빛 같은 나의 사랑아                       아이유 (IU)
48  49위                 끝사랑                            임영웅
58  59위           사랑은 늘 도망가  The Kid LAROI & Justin Bieber
63  64위              나의 첫사랑  The Kid LAROI & Justin Bieber
81  82위  다시 사랑한다면 (김필 Ver.)               멜로망스 (MeloMance)
88  89위        별빛 같은 나의 사랑아                   마크툽 (Maktub)
98  99위                 끝사랑                            임영웅

In [152]:
melon[melon['곡 명'].str.contains('사랑')]

     순위                                곡 명         가수
4    5위                          사랑은 늘 도망가        임영웅
24  25위                       별빛 같은 나의 사랑아        임영웅
27  28위                 다시 사랑한다면 (김필 Ver.)        임영웅
34  35위                                끝사랑        임영웅
57  58위                             나의 첫사랑        다비치
60  61위          어떻게 이별까지 사랑하겠어, 널 사랑하는 거지  AKMU (악뮤)
93  94위  사랑은 언제나 목마르다 (N번째 연애 X 이해리 (다비치))  이해리 (다비치)